name: Test SHOGun

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11.0.9
          java-package: jdk
          architecture: x64

      - name: Handle caching of maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test SHOGun with Maven
        run: mvn -B test